//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoujinGameProject.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoujinGameProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap douguya_dt {
            get {
                object obj = ResourceManager.GetObject("douguya_dt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap dungeon06 {
            get {
                object obj = ResourceManager.GetObject("dungeon06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_bg_000_0 {
            get {
                object obj = ResourceManager.GetObject("g_bg_000_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_bg_001_0 {
            get {
                object obj = ResourceManager.GetObject("g_bg_001_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_bg_002_0 {
            get {
                object obj = ResourceManager.GetObject("g_bg_002_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_bg_002_1 {
            get {
                object obj = ResourceManager.GetObject("g_bg_002_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_bg_003_0 {
            get {
                object obj = ResourceManager.GetObject("g_bg_003_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_000_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_000_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_000_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_000_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_000_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_000_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_001_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_001_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_001_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_001_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_001_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_001_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_002_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_002_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_002_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_002_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_002_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_002_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_003_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_003_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_003_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_003_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_003_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_003_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_004_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_004_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_004_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_004_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_004_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_004_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_005_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_005_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_005_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_005_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_005_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_005_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_006_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_006_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_006_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_006_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_006_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_006_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_007_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_007_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_007_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_007_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_007_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_007_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_008_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_008_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_008_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_008_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_008_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_008_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_009_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_009_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_009_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_009_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_009_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_009_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_010_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_010_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_010_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_010_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_010_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_010_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_011_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_011_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_011_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_011_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_011_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_011_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_000_0 {
            get {
                object obj = ResourceManager.GetObject("g_ev_000_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_000_1 {
            get {
                object obj = ResourceManager.GetObject("g_ev_000_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_000_2 {
            get {
                object obj = ResourceManager.GetObject("g_ev_000_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_001_0 {
            get {
                object obj = ResourceManager.GetObject("g_ev_001_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_001_1 {
            get {
                object obj = ResourceManager.GetObject("g_ev_001_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_001_2 {
            get {
                object obj = ResourceManager.GetObject("g_ev_001_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap hiroba_dt {
            get {
                object obj = ResourceManager.GetObject("hiroba_dt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap hiroba_ev {
            get {
                object obj = ResourceManager.GetObject("hiroba_ev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap hiroba_nt {
            get {
                object obj = ResourceManager.GetObject("hiroba_nt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kyoukai_dt {
            get {
                object obj = ResourceManager.GetObject("kyoukai_dt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kyoukai_ev {
            get {
                object obj = ResourceManager.GetObject("kyoukai_ev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kyoukai_nt {
            get {
                object obj = ResourceManager.GetObject("kyoukai_nt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap lidy_0_0 {
            get {
                object obj = ResourceManager.GetObject("lidy_0_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Nameform {
            get {
                object obj = ResourceManager.GetObject("Nameform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream に類似した型 System.IO.UnmanagedMemoryStream のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ohayougozaimasu_02 {
            get {
                return ResourceManager.GetStream("ohayougozaimasu_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap rouya_nt {
            get {
                object obj = ResourceManager.GetObject("rouya_nt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap sakaba_ntr {
            get {
                object obj = ResourceManager.GetObject("sakaba_ntr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap sara_0_0 {
            get {
                object obj = ResourceManager.GetObject("sara_0_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap sara_0_2 {
            get {
                object obj = ResourceManager.GetObject("sara_0_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap syoko_dt {
            get {
                object obj = ResourceManager.GetObject("syoko_dt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap syoko_nt {
            get {
                object obj = ResourceManager.GetObject("syoko_nt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   6
        ///3
        ///id,name,attribute,price,attack,defence
        ///item_w_0001,木刀,weapon,100,10,0
        ///item_w_0002,銅の剣,weapon,500,20,0
        ///item_w_0003,鉄の剣,weapon,1200,35,0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Textform {
            get {
                object obj = ResourceManager.GetObject("Textform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap yadoya_dt {
            get {
                object obj = ResourceManager.GetObject("yadoya_dt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap yadoya_ev {
            get {
                object obj = ResourceManager.GetObject("yadoya_ev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap yadoya_ntr {
            get {
                object obj = ResourceManager.GetObject("yadoya_ntr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   
        ///
        ///END:
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string エンディング {
            get {
                return ResourceManager.GetString("エンディング", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///// オープニングシナリオ
        /////senario1
        ///
        ///背景 教会夕:
        ///
        ///IN サラ:
        ///
        ///Text:
        ///;
        ///
        ///Text:
        ///私の名前はサラ。;
        ///
        //////////////////////////
        /////	デバッグ用
        //////////////////////////
        /////背景 教会昼:
        ///
        /////END:
        //////////////////////////
        ///
        ///Text:
        ///この小さな町にただ一つある教会で
        ///シスターをしています。;
        ///
        ///Text:
        ///日々町の皆さんの健康やこの世界の平和を願って
        ///お祈りをするのが私の仕事です。;
        ///
        ///マリー:
        ///あ、サラ、ちょうどいいところに。;
        ///
        ///マリー:
        ///もう言ってあったと思うけど、
        ///今夜はバディオの大聖堂で神父会があるから、;
        ///
        ///マリー:
        ///神父様と私は出かけてくるわね。;
        ///
        ///マリー:
        ///今夜は帰らないから。;
        ///
        ///マリー:
        ///戸締りとか、見回りとか、
        ///リディと手分けしてチェックしておいてね。;
        ///
        ///サラ:
        ///はい、わかりました、姉様。;
        ///
        ///Text:
        ///この人はシスターマリー。私の先輩です。;
        ///
        ///Text:
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string オープニング {
            get {
                return ResourceManager.GetString("オープニング", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///
        ///
        ///
        ///END:
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string スキル取得 {
            get {
                return ResourceManager.GetString("スキル取得", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //休息
        ///
        ///If( 時刻 &gt;= 19 ) [L_LEST_BGP_002]:
        ///If( 時刻 &gt;= 16 ) [L_LEST_BGP_001]:
        ///
        ///背景 部屋昼:
        ///
        ///JMP [L_LEST_BGP_EXT]:
        ///
        ///[L_LEST_BGP_001]:
        ///背景 部屋夕:
        ///
        ///JMP [L_LEST_BGP_EXT]:
        ///
        ///[L_LEST_BGP_002]:
        ///背景 部屋夜:
        ///
        ///[L_LEST_BGP_EXT]:
        ///
        ///Text:
        ///自分の部屋に来ました。;
        ///
        ///サラ:
        ///どうしようかな……;
        ///
        ///
        ///
        ///[L_LEST_SEL_0000]:
        ///
        ///////////触手成長度分岐/////////
        ///If( 触手成長度 &gt;= 100 ) [L_LEST_SEL_2000]:
        ///If( 触手成長度 &gt;= 50 ) [L_LEST_SEL_1000]:
        ///
        //////////////////////////////////
        /////触手成長度 &gt;= 0
        ///If( 性欲値 &gt;= 80 ) [L_LEST_SEL_0400]:
        ///If( 性欲値 &gt;= 40 ) [L_LEST_SEL_0200]:
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 休息 {
            get {
                return ResourceManager.GetString("休息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        /////体力切れ
        ///
        ///
        ///If( 体力 &gt;= 10 ) [HP_RUNOUT_0000]:
        ///JMP [HP_RUNOUT_1000]:
        ///
        ///[HP_RUNOUT_0000]:
        /////体力切れ間近
        ///サラ:
        ///はぁ……はぁ……;
        ///
        ///サラ:
        ///きょ……今日はもう疲れちゃった……
        ///寝ようかな……;
        ///
        ///サラ:
        ///私は今日はもう休むことにしました。;
        ///
        ///Plus:
        ///体力が60回復した。;
        ///
        ///計算 体力 += 60:
        ///
        ///Text:
        ///…………;
        ///
        ///計算 時刻 = 6:
        ///
        ///背景 部屋昼:
        ///
        ///Text:
        ///朝になりました。;
        ///
        ///JMP [HP_RUNOUT_EXT]:
        ///
        ///
        ///[HP_RUNOUT_1000]:
        /////体力切れ
        ///サラ:
        ///もう……だめ……;
        ///
        ///Text:
        ///バタッ……;
        ///
        ///Text:
        ///私は疲れ果てて倒れてしまいました。;
        ///
        ///Text:
        ///…………;
        ///
        /////If( 乱数 &gt; 90 ) [HP_RUNOUT_1000]:
        ///
        ///サラ:
        ///うぅん……ここは？;
        ///
        ///マリー:
        ///目が覚めたかい？;
        ///
        ///サラ:
        ///あっ……姉様……;
        ///
        ///マリー: [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 体力切れ {
            get {
                return ResourceManager.GetString("体力切れ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///
        ///END:
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 性欲限界 {
            get {
                return ResourceManager.GetString("性欲限界", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //教会
        ///
        ///If( 時刻 &gt;= 19 ) [L_CHRC_SEL_NT]:
        ///If( 時刻 &gt;= 16 ) [L_CHRC_SEL_EV]:
        ///
        ///背景 教会昼:
        ///
        ///JMP [L_CHRC_SEL_START]:
        ///
        ///[L_CHRC_SEL_EV]:
        ///背景 教会夕:
        ///
        ///JMP [L_CHRC_SEL_START]:
        ///
        ///[L_CHRC_SEL_NT]:
        ///背景 教会夜:
        ///
        ///[L_CHRC_SEL_START]:
        ///
        ///サラ:
        ///教会でお勤めをしようっと;
        ///
        ///サラ:
        ///何をしようかな？;
        ///
        ///
        ///////////////////////////////////////////////////////////
        ///////////////////////////////////////////////////////////
        ///
        ///If( 道徳心 &lt; 40 ) [L_CHRC_SEL_1000]:
        ///
        ///選択肢:
        ///祈りを捧げる;
        ///マリー姉様の部屋に行く;
        ///リディの部屋に行く;
        ///選択肢終:
        ///
        ///If( 選択番号 == 1 ) [L_CHRC_PRAY]:
        ///If( 選択番号 == [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 教会 {
            get {
                return ResourceManager.GetString("教会", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///
        ///END:
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 気力切れ {
            get {
                return ResourceManager.GetString("気力切れ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///背景 
        ///
        ///END: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 読書 {
            get {
                return ResourceManager.GetString("読書", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 露出 {
            get {
                return ResourceManager.GetString("露出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream に類似した型 System.IO.UnmanagedMemoryStream のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream 音楽 {
            get {
                return ResourceManager.GetStream("音楽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //魔物パート
        ///
        ///
        ///背景 牢屋:
        /////////[塩味]　魔物化したら牢屋の背景明るくしたい
        ///
        ///
        ///If( 日数 == 1 ) [L_DEVIL_FIRST]:
        ///JMP [L_DEVIL_START]:
        ///
        ///
        ///[L_DEVIL_FIRST]:
        ///
        /////一回目
        ///魔物:
        ///グフフ、やはり来たか小娘。
        ///露出の快楽が忘れられなかったと見えるな;
        ///
        ///サラ:
        ///……;
        ///
        ///魔物:
        ///心配する必要はなかろう。
        ///俺を開放するには１０００００マージもの魔力が必要だ。
        ///
        ///魔物:
        ///貴様がいくつか性癖を得たところで、
        ///俺がこの牢屋から出られることはあるまい。;
        ///
        ///魔物:
        ///最も、貴様が欲に溺れて浅ましく快楽を求めたり、
        ///この俺に忠誠を誓うようになったり
        ///しなければの話だが、な……;
        ///
        ///サラ:
        ///……なっ……;
        ///
        ///サラ:
        ///……そんなこと、あり得ません。;
        ///
        ///魔物:
        ///なら、安心して魔力をこの封印に注ぎ込め。
        ///相応の快楽を与えてやるぞ？;
        ///
        ///サラ:
        ///…………;
        ///
        ///魔物:
        ///１００マージ魔力を注ぎ込むごとに
        ///このコイン、&quot;魔貨&quot;を１枚やろう。;
        ///
        ///魔物:
        ///魔貨 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 魔物パート {
            get {
                return ResourceManager.GetString("魔物パート", resourceCulture);
            }
        }
    }
}
