//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoujinGameProject.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoujinGameProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap douguya_dt {
            get {
                object obj = ResourceManager.GetObject("douguya_dt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap dungeon06 {
            get {
                object obj = ResourceManager.GetObject("dungeon06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_bg_000_0 {
            get {
                object obj = ResourceManager.GetObject("g_bg_000_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_bg_001_0 {
            get {
                object obj = ResourceManager.GetObject("g_bg_001_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_bg_002_0 {
            get {
                object obj = ResourceManager.GetObject("g_bg_002_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_bg_002_1 {
            get {
                object obj = ResourceManager.GetObject("g_bg_002_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_bg_003_0 {
            get {
                object obj = ResourceManager.GetObject("g_bg_003_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_000_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_000_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_000_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_000_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_000_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_000_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_001_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_001_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_001_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_001_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_001_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_001_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_002_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_002_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_002_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_002_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_002_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_002_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_003_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_003_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_003_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_003_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_003_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_003_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_004_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_004_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_004_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_004_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_004_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_004_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_005_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_005_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_005_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_005_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_005_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_005_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_006_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_006_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_006_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_006_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_006_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_006_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_007_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_007_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_007_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_007_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_007_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_007_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_008_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_008_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_008_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_008_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_008_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_008_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_009_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_009_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_009_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_009_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_009_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_009_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_010_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_010_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_010_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_010_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_010_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_010_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_011_0 {
            get {
                object obj = ResourceManager.GetObject("g_btn_011_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_011_1 {
            get {
                object obj = ResourceManager.GetObject("g_btn_011_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_btn_011_2 {
            get {
                object obj = ResourceManager.GetObject("g_btn_011_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_chara_000_0 {
            get {
                object obj = ResourceManager.GetObject("g_chara_000_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_chara_000_1 {
            get {
                object obj = ResourceManager.GetObject("g_chara_000_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_chara_000_2 {
            get {
                object obj = ResourceManager.GetObject("g_chara_000_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_chara_001_0 {
            get {
                object obj = ResourceManager.GetObject("g_chara_001_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_chara_001_1 {
            get {
                object obj = ResourceManager.GetObject("g_chara_001_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_chara_001_2 {
            get {
                object obj = ResourceManager.GetObject("g_chara_001_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_000_0 {
            get {
                object obj = ResourceManager.GetObject("g_ev_000_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_000_1 {
            get {
                object obj = ResourceManager.GetObject("g_ev_000_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_000_2 {
            get {
                object obj = ResourceManager.GetObject("g_ev_000_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_001_0 {
            get {
                object obj = ResourceManager.GetObject("g_ev_001_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_001_1 {
            get {
                object obj = ResourceManager.GetObject("g_ev_001_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap g_ev_001_2 {
            get {
                object obj = ResourceManager.GetObject("g_ev_001_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap hiroba_dt {
            get {
                object obj = ResourceManager.GetObject("hiroba_dt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap hiroba_ev {
            get {
                object obj = ResourceManager.GetObject("hiroba_ev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap hiroba_nt {
            get {
                object obj = ResourceManager.GetObject("hiroba_nt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kyoukai_dt {
            get {
                object obj = ResourceManager.GetObject("kyoukai_dt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kyoukai_ev {
            get {
                object obj = ResourceManager.GetObject("kyoukai_ev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kyoukai_nt {
            get {
                object obj = ResourceManager.GetObject("kyoukai_nt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap lidy_0_0 {
            get {
                object obj = ResourceManager.GetObject("lidy_0_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap rouya_nt {
            get {
                object obj = ResourceManager.GetObject("rouya_nt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap sakaba_ntr {
            get {
                object obj = ResourceManager.GetObject("sakaba_ntr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap sara_0_0 {
            get {
                object obj = ResourceManager.GetObject("sara_0_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap sara_0_2 {
            get {
                object obj = ResourceManager.GetObject("sara_0_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap syoko_dt {
            get {
                object obj = ResourceManager.GetObject("syoko_dt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap syoko_nt {
            get {
                object obj = ResourceManager.GetObject("syoko_nt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   6
        ///3
        ///id,name,attribute,price,attack,defence
        ///item_w_0001,木刀,weapon,100,10,0
        ///item_w_0002,銅の剣,weapon,500,20,0
        ///item_w_0003,鉄の剣,weapon,1200,35,0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap yadoya_dt {
            get {
                object obj = ResourceManager.GetObject("yadoya_dt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap yadoya_ev {
            get {
                object obj = ResourceManager.GetObject("yadoya_ev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap yadoya_ntr {
            get {
                object obj = ResourceManager.GetObject("yadoya_ntr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   
        ///// オープニングシナリオ
        /////senario1
        ///
        ///IN サラ:
        ///
        ///Text:
        ///私の名前はサラ。;
        ///
        ///Text:
        ///この小さな町にただ一つある教会で
        ///シスターをしています。;
        ///
        ///Text:
        ///日々町の皆さんの健康やこの世界の平和を願って
        ///お祈りをするのが私の仕事です。;
        ///
        ///マリー:
        ///あ、サラ、ちょうどいいところに。;
        ///
        ///マリー:
        ///もう言ってあったと思うけど、
        ///今夜はバディオの大聖堂で神父会があるから、;
        ///
        ///マリー:
        ///神父様と私は出かけてくるわね。;
        ///
        ///マリー:
        ///今夜は帰らないから。;
        ///
        ///マリー:
        ///戸締りとか、見回りとか、
        ///リディと手分けしてチェックしておいてね。;
        ///
        ///サラ:
        ///はい、わかりました、姉様。;
        ///
        ///Text:
        ///この人はシスターマリー。私の先輩です。;
        ///
        ///Text:
        ///姉様と言っても、本当のお姉さんというわけではなく、
        ///この教会ではシスターが目上のシスターを呼ぶときは
        ///&quot;姉様&quot;って呼ぶものなんです。;
        ///
        ///Text:
        ///とても気さくで面倒見が良く、
        ///誰とでもすぐに打ち解けられるし、正義感が強い…
        ///私の憧れです。;
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string オープニング {
            get {
                return ResourceManager.GetString("オープニング", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///
        ///Text:
        ///自分の部屋に来ました。;
        ///
        ///サラ:
        ///どうしようかな……;
        ///
        ///
        ///
        ///[L_LEST_SEL_0000]:
        ///
        ///////////触手成長度分岐/////////
        ///If( 触手成長度 &gt;= 100 ) [L_LEST_SEL_2000]:
        ///If( 触手成長度 &gt;= 50 ) [L_LEST_SEL_1000]:
        ///
        //////////////////////////////////
        /////触手成長度 &gt;= 0
        ///If( 性欲値 &gt;= 80 ) [L_LEST_SEL_0400]:
        ///If( 性欲値 &gt;= 40 ) [L_LEST_SEL_0200]:
        ///
        ///If( 道徳心 &lt; 20 ) [L_LEST_0100]:
        ///If( 道徳心 &lt; 60 ) [L_LEST_0050]:
        ///JMP [L_LEST_0000]:
        ///
        ///[L_LEST_SEL_0200]:
        ///If( 道徳心 &lt; 20 ) [L_LEST_0300]:
        ///If( 道徳心 &lt; 60 ) [L_LEST_0250]:
        ///JMP [L_LEST_0200]:
        ///
        ///[L_LEST_SEL_0400]:
        ///If( 道徳 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 休息 {
            get {
                return ResourceManager.GetString("休息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //教会
        ///
        ///サラ:
        ///教会でお勤めをしようっと;
        ///
        ///サラ:
        ///何をしようかな？;
        ///
        ///
        ///////////////////////////////////////////////////////////
        ///////////////////////////////////////////////////////////
        ///
        ///If( 道徳心 &lt; 40 ) [L_CHRC_SEL_1000]:
        ///
        ///選択肢:
        ///祈りを捧げる;
        ///マリー姉様と話す;
        ///リディと話す;
        ///選択肢終:
        ///
        ///If( 選択番号 == 1 ) [L_CHRC_PRAY]:
        ///If( 選択番号 == 2 ) [L_CHRC_MARY]:
        ///JMP [L_CHRC_LIDY]:
        ///
        ///
        ///[L_CHRC_SEL_1000]:
        ///
        ///選択肢:
        ///祈りを捧げるふりをする;
        ///マリー姉様と話す;
        ///リディと話す;
        ///選択肢終:
        ///
        ///If( 選択番号 == 1 ) [L_CHRC_PRAY_FAKE]:
        ///If( 選択番号 == 2 ) [L_CHRC_MARY]:
        ///JMP [L_CHRC_LIDY]:
        ///
        //////////////// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 教会 {
            get {
                return ResourceManager.GetString("教会", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 読書 {
            get {
                return ResourceManager.GetString("読書", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream に類似した型 System.IO.UnmanagedMemoryStream のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream 音楽 {
            get {
                return ResourceManager.GetStream("音楽", resourceCulture);
            }
        }
    }
}
